version: '2'
volumes:
  ovpn-data-zappa:
    external: true
  tsunami_fail2ban_data: 
    external: true 
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: dougw/openvpn
    container_name: vpn
    restart: always
    ports:
     - "1194:1194/udp"
     - "80:80"
     - "23:2777"
     - "2777:2777"
     - "443:443"
     - "1234:1234"
    restart: always
    volumes:
     - ovpn-data-zappa:/etc/openvpn
